import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main-div-index">
        <img
          className="logo"
          src="https://i.ibb.co/17JXpbw/matchmakr-high-resolution-logo-color-on-transparent-background.png"
        ></img>
        <h2 style={{width: '50%', display: 'flex', justifyContent: 'center', alignItems:'center', textAlign: 'center'}}>
          Find the perfect match, weather you're looking for roles or employees, we got you covered!
        </h2>
        <div className="button-div">
          <Link href="/employee" className="employee-button" style={{textDecoration: 'none'}}>
          I'm an Employee
          </Link>
          <Link href="/employer" className="employee-button" style={{textDecoration: 'none'}}>I'm an Employer</Link>
        </div>
      </div>
    </>
  );
}
